title: Ningninger's Blog
description: 欢迎来到我的博客！我相信知识的分享是推动个人成长和社区发展的重要途径之一。在这个博客中，我将分享和记录我在计算机科学与技术领域的学习心得、技术探索和项目经验。无论是探讨最新的编程语言、算法和数据结构，还是分享解决技术难题的方法，我都希望在记录我的学习之旅的同时能够为您提供有价值的内容。除了技术方面，我还将分享一些关于学习和生活的见解。在这个充满挑战和机遇的领域里，我希望自己不仅能注重技术能力的提升，也关注个人成长和心理健康。我深知学习是一个不断改进的过程，如果您发现任何内容上的错误或偏差，请及时与我联系。学习之路上难免会有犯错之处，我谨此致歉，并感谢您的理解和支持。
theme: just-the-docs


# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/favicon.png"


# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/images/favicon2.ico"


url: https://ningninger.github.io

aux_links:
  Template Repository: https://github.com/ningninger/ningninger.github.io


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
