title: ningninger
description: 欢迎来到我的博客！我相信知识的分享是推动个人成长和社区发展的重要途径之一。在这个博客中，我将分享和记录我在计算机科学与技术领域的学习心得、技术探索和项目经验。无论是探讨最新的编程语言、算法和数据结构，还是分享解决技术难题的方法，我都希望在记录我的学习之旅的同时能够为您提供有价值的内容。除了技术方面，我还将分享一些关于学习和生活的见解。在这个充满挑战和机遇的领域里，我希望自己不仅能注重技术能力的提升，也关注个人成长和心理健康。我深知学习是一个不断改进的过程，如果您发现任何内容上的错误或偏差，请及时与我联系。学习之路上难免会有犯错之处，我谨此致歉，并感谢您的理解和支持。
theme: just-the-docs

url: https://ningninger.github.io

# Aux links for the upper right navigation
aux_links:
  "Blog":
    - "//github.com/ningninger/ningninger.github.io"
  "Github":
    - "//github.com/ningninger/"
  

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
  # Focus the search input by pressing `ctrl + focus_shortcut_key` (or `cmd + focus_shortcut_key` on macOS)
  focus_shortcut_key: 'k'


mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"


markdown: kramdown

pygments: true


# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true


# Heading anchor links appear on hover over h1-h6 tags in page content
# allowing users to deep link to a particular heading on a page.
#
# Supports true (default) or false
heading_anchors: true


# Color scheme supports "light" (default) and "dark"
color_scheme: light

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red


# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)


ga_tracking: "UA-1234567-89,G-1AB234CDE5"

back_to_top: true
back_to_top_text: "Back to top"